In [1]:
# Task-1 : 1

# Step 1: If the system is 64 bit download the file using the below link.
# Link: https://drive.google.com/file/d/0Bxr27gVaXO5sNXVpUXVvRm1iU1k/view?usp=sharing
# Skip the step 2 and 3 if your system is 64 bit
# Step 2: Click on the below link to go to the anaconda installer
# https://www.anaconda.com/download/#download
# Step 3: On clicking the above link below screen pops up,select the python 3.6 option and click
# on download.

import numpy as np
np.random.seed(0)
x1 = np.random.randint(4,size = 6)
#print(x1)
x2 = np.random.randint(4,size = (3,4))
#print(x2)
x3 = np.random.randint(4,size = (3,4,5))
print(x3)

[[[2 1 2 3 3]
  [2 0 1 1 1]
  [1 0 1 0 3]
  [0 3 1 2 3]]

 [[3 0 2 3 0]
  [1 3 1 3 3]
  [2 3 0 1 1]
  [1 3 0 3 2]]

 [[0 3 3 2 3]
  [2 3 0 2 0]
  [0 0 1 1 2]
  [0 0 1 3 0]]]


In [2]:
# Task-1 : 2

# Write a program which will find all such numbers which are divisible by 7 but are not a multiple
# of 5, between 2000 and 3200 (both included). The numbers obtained should be printed in a
# comma-separated sequence on a single line.

lower = 2000
upper = 3200
r = range(lower,upper+1)
L = list(r)

res = 0*L
indiv = 0*L

#Index = list(range(0,len(L)))
for val in L:
    remainder7 = val % 7
    remainder5 = val % 5
    #print(remainder[val])
    if(remainder7==0 and remainder5!=0):
        res.append(val)
        #print(list(res))
        #print(res[val])        
    else:
        indiv.append(val)
print("The nos. are ",list(res))  
print("The total nos. are ",len(res))

The nos. are  [2002, 2009, 2016, 2023, 2037, 2044, 2051, 2058, 2072, 2079, 2086, 2093, 2107, 2114, 2121, 2128, 2142, 2149, 2156, 2163, 2177, 2184, 2191, 2198, 2212, 2219, 2226, 2233, 2247, 2254, 2261, 2268, 2282, 2289, 2296, 2303, 2317, 2324, 2331, 2338, 2352, 2359, 2366, 2373, 2387, 2394, 2401, 2408, 2422, 2429, 2436, 2443, 2457, 2464, 2471, 2478, 2492, 2499, 2506, 2513, 2527, 2534, 2541, 2548, 2562, 2569, 2576, 2583, 2597, 2604, 2611, 2618, 2632, 2639, 2646, 2653, 2667, 2674, 2681, 2688, 2702, 2709, 2716, 2723, 2737, 2744, 2751, 2758, 2772, 2779, 2786, 2793, 2807, 2814, 2821, 2828, 2842, 2849, 2856, 2863, 2877, 2884, 2891, 2898, 2912, 2919, 2926, 2933, 2947, 2954, 2961, 2968, 2982, 2989, 2996, 3003, 3017, 3024, 3031, 3038, 3052, 3059, 3066, 3073, 3087, 3094, 3101, 3108, 3122, 3129, 3136, 3143, 3157, 3164, 3171, 3178, 3192, 3199]
The total nos. are  138


In [3]:
# Task-1 : 3

# Write a Python program to accept the user's first and last name and then getting them printed in
# the the reverse order with a space between first name and last name.

FirstName = input("Please type your First Name: ")
LastName = input("Please type your Last Name: ")
Name = []
Name.append(FirstName)
Name.append(' ')
Name.append(LastName)
Nm = Name

Nm.reverse()
print("Your Name in reverse order : " + Nm[0] + Nm[1] + Nm[2])

Please type your First Name: Debasish
Please type your Last Name: Bhaskar
Your Name in reverse order : Bhaskar Debasish


In [4]:
# Task-1 : 4

# Write a Python program to find the volume of a sphere with diameter 12 cm.

def volume_sphere(dia_in_meter):
     import math
     PI = math.pi
     radius_in_meter = dia_in_meter/2
     r=radius_in_meter
     C=pow(r,3)
     V=(4/3)*(PI)*(C)
     print("The volume of the sphere in Cubic Meter is as below : ")
     return V
     
Diameter=input('Enter the Diameter of the sphere in meter : ')
D = float(Diameter)
volume_sphere(D)

Enter the Diameter of the sphere in meter : 0.12
The volume of the sphere in Cubic Meter is as below : 


0.0009047786842338602

In [5]:
# Task-2 : 1

# Write a program which accepts a sequence of comma-separated numbers from console and
# generate a list.

Sequence = []
Sequence = input('Enter the comma separated sequence : ')
S = Sequence
print(S)
L = S.split(',')
print("The List : " + str(L))

Enter the comma separated sequence : 2,34,87,900,127,43,1006,46,96
2,34,87,900,127,43,1006,46,96
The List : ['2', '34', '87', '900', '127', '43', '1006', '46', '96']


In [6]:
# Task-2 : 2

# Create the below pattern using nested for loop in Python.

for num in range(6):
    for val in range(num):
        
        print ('*', end = " ")
    
    print("\n")  # new line after each row to display pattern correctly
L = list(range(5))
L.reverse()
for num2 in L:
    for val2 in range(num2):
        print ('*', end = " ")
    print("\n")  # new line after each row to display pattern correctly



* 

* * 

* * * 

* * * * 

* * * * * 

* * * * 

* * * 

* * 

* 





In [7]:
# Task-2 : 3

# Write a Python program to reverse a word after accepting the input from the user.

InputWord = []
InputWord = input('Enter the input word : ')
print("The output word : " + InputWord[::-1])

Enter the input word : AcadGild
The output word : dliGdacA


In [8]:
# Task-2 : 4

# Write a Python Program to print the given string in the format specified in the sample output.
# WE, THE PEOPLE OF INDIA, having solemnly resolved to constitute India into a
# SOVEREIGN, SOCIALIST, SECULAR, DEMOCRATIC REPUBLIC and to secure to all
# its citizens

print("WE, THE PEOPLE OF INDIA,")
print('      having solemnly resolved to constitute India into a SOVEREIGN, !')
print('\t     SOCIALIST, SECULAR, DEMOCRATIC REPUBLIC'.expandtabs())
print('\t      and to secure to all its citizens')

WE, THE PEOPLE OF INDIA,
      having solemnly resolved to constitute India into a SOVEREIGN, !
             SOCIALIST, SECULAR, DEMOCRATIC REPUBLIC
	      and to secure to all its citizens
